### ISSUE TITLE
Missing Subscription 

### ISSUE THREAD

**Issue by iacavd** [srozemuller/AzAvd#17]
While executing the below script , we receive this error 

(We have multiple subscriptions) 
Select-Subscription doesn't help 

Error:  WARNING: Someting went wrong when crawling for info, {"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}

Code:

Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName | Select-Object vmLatestVersion, hostpoolName, sessionhostName, currentImageVersion, lastVersion

Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName -NotLatest | ForEach-Object { Update-AvdSessionhostDrainMode -HostpoolName $_.Hostpoolname -ResourceGroupName $AVDArmResourcesResourceGroupName -SessionHostName $_.sessionHostName -AllowNewSession $true }

#Remove Session Host from Host Pool
Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName -NotLatest | ForEach-Object {Remove-AvdSessionhost -HostpoolName $_.Hostpoolname -ResourceGroupName $AVDArmResourcesResourceGroupName -SessionHostName $_.sessionHostName}

#Remove VM and Associated Resources
Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName -NotLatest | ForEach-Object {
    $sessionHostInfo = @{
        HostpoolName = $_.HostpoolName
        ResourceGroupName = $AVDArmResourcesResourceGroupName
        SessionHostName = $_.SessionHostName
    }
    
    $sessionHost = Get-AvdSessionHostResources @sessionHostInfo
    Remove-AzResource -ResourceId $sessionHost.Id -Force
    Remove-AzResource -ResourceId $sessionHost.StorageProfile.OsDisk.ManagedDisk.id -Force
    Remove-AzResource -ResourceId (Get-AvdNetworkInfo @sessionHostInfo).nicId -Force
}

**Comment by srozemuller** [comment]
Bug found and fixed. Ready to update in the next version. Planning to update the module in the next few days.

**Comment by srozemuller** [comment]
@iacavd I fixed the bug in the beta version. You could download the version here: https://github.com/srozemuller/AzAvd/releases/tag/2.1.4-5-beta

**Comment by iacavd** [comment]
PS C:\AzAVD> Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName
WARNING: Someting went wrong when crawling for info, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}
WARNING: Someting went wrong when crawling for info, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}
WARNING: Someting went wrong when crawling for info, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}
WARNING: Someting went wrong when crawling for info, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}

name        : AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-10.gad.##############
id          : /subscriptions/##############/resourcegroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.DesktopVirtualization/hostpools/AVD-HostPool-SND-FJ-POC-AFC-01/sessionhosts/FJAVDAFC-10.gad.##############
              ##############
type        : Microsoft.DesktopVirtualization/hostpools/sessionhosts
properties  : @{lastHeartBeat=3/14/2022 2:43:27 PM; statusTimestamp=3/10/2022 2:34:11 PM; lastUpdateTime=3/10/2022 2:34:11 PM; sessions=0; agentVersion=1.0.4119.1500; allowNewSession=False; assignedUser=; status=Available;
              osVersion=10.0.19043; sxSStackVersion=rdp-sxs220104110; updateState=Succeeded; updateErrorMessage=; sessionHostHealthCheckResults=System.Object[];
              resourceId=/subscriptions/##############/resourceGroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.Compute/virtualMachines/FJAVDAFC-10; virtualMachineId=b86801f1-b6b9-4bb5-a6da-b30fbf0c6c74;
              objectId=7f212fbc-654e-417c-bf1a-d1f5f55b79c2}
systemData  : @{createdBy=; createdByType=; createdAt=3/10/2022 2:22:55 PM; lastModifiedBy=9cdead84-a844-4324-93f2-b2e6bb768d07; lastModifiedByType=Application; lastModifiedAt=3/14/2022 12:09:51 PM}
vmResources : @{name=FJAVDAFC-10; id=/subscriptions/##############/resourceGroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.Compute/virtualMachines/FJAVDAFC-10; type=Microsoft.Compute/virtualMachines;
              location=francecentral; tags=; properties=; resources=System.Object[]}
imageInfo   :

name        : AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-11.gad.##############
id          : /subscriptions/##############/resourcegroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.DesktopVirtualization/hostpools/AVD-HostPool-SND-FJ-POC-AFC-01/sessionhosts/FJAVDAFC-11.gad.##############
              ##############
type        : Microsoft.DesktopVirtualization/hostpools/sessionhosts
properties  : @{lastHeartBeat=3/14/2022 2:43:02 PM; statusTimestamp=3/10/2022 2:34:13 PM; lastUpdateTime=3/10/2022 2:34:13 PM; sessions=0; agentVersion=1.0.4119.1500; allowNewSession=False; assignedUser=; status=Available;
              osVersion=10.0.19043; sxSStackVersion=rdp-sxs220104110; updateState=Succeeded; updateErrorMessage=; sessionHostHealthCheckResults=System.Object[];
              resourceId=/subscriptions/##############/resourceGroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.Compute/virtualMachines/FJAVDAFC-11; virtualMachineId=3f8119f8-0777-447a-ad3c-9a2fbb52672b;
              objectId=56d64254-457e-4327-ace0-5bfeb86cfeb0}
systemData  : @{createdBy=; createdByType=; createdAt=3/10/2022 2:22:58 PM; lastModifiedBy=SESA621467@se.com; lastModifiedByType=User; lastModifiedAt=3/14/2022 12:11:04 PM}
vmResources : @{name=FJAVDAFC-11; id=/subscriptions/##############/resourceGroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.Compute/virtualMachines/FJAVDAFC-11; type=Microsoft.Compute/virtualMachines;
              location=francecentral; tags=; properties=; resources=System.Object[]}
imageInfo   :

name        : AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-3.gad.##############
id          : /subscriptions/##############/resourcegroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.DesktopVirtualization/hostpools/AVD-HostPool-SND-FJ-POC-AFC-01/sessionhosts/FJAVDAFC-3.gad.##############
type        : Microsoft.DesktopVirtualization/hostpools/sessionhosts
properties  : @{lastHeartBeat=3/14/2022 12:42:31 PM; statusTimestamp=3/9/2022 7:22:07 AM; lastUpdateTime=3/9/2022 7:22:07 AM; sessions=0; agentVersion=1.0.4119.1500; allowNewSession=True; assignedUser=; status=Available;
              osVersion=10.0.19043; sxSStackVersion=rdp-sxs220104110; updateState=Succeeded; updateErrorMessage=; sessionHostHealthCheckResults=System.Object[];
              resourceId=/subscriptions/##############/resourceGroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.Compute/virtualMachines/FJAVDAFC-3; virtualMachineId=bbc574e0-32e2-4387-96be-b974424d4e8f;
              objectId=c689c555-82db-4d47-943c-1b246da2b08b}
systemData  : @{createdBy=; createdByType=; createdAt=3/9/2022 3:40:23 AM; lastModifiedBy=9cdead84-a844-4324-93f2-b2e6bb768d07; lastModifiedByType=Application; lastModifiedAt=3/10/2022 3:53:21 PM}
vmResources : @{name=FJAVDAFC-3; id=/subscriptions/##############/resourceGroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.Compute/virtualMachines/FJAVDAFC-3; type=Microsoft.Compute/virtualMachines;
              location=francecentral; tags=; properties=; resources=System.Object[]}
imageInfo   :

name        : AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-9.gad.##############
id          : /subscriptions/##############/resourcegroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.DesktopVirtualization/hostpools/AVD-HostPool-SND-FJ-POC-AFC-01/sessionhosts/FJAVDAFC-9.gad.##############
type        : Microsoft.DesktopVirtualization/hostpools/sessionhosts
properties  : @{lastHeartBeat=3/14/2022 12:25:25 PM; statusTimestamp=3/10/2022 2:34:11 PM; lastUpdateTime=3/10/2022 2:34:11 PM; sessions=2; agentVersion=1.0.4119.1500; allowNewSession=True; assignedUser=; status=Available;
              osVersion=10.0.19043; sxSStackVersion=rdp-sxs220104110; updateState=Succeeded; updateErrorMessage=; sessionHostHealthCheckResults=System.Object[];
              resourceId=/subscriptions/##############/resourceGroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.Compute/virtualMachines/FJAVDAFC-9; virtualMachineId=20b251d5-6f37-46c2-a537-cba4aa1be758;
              objectId=c78a6e56-535b-47a4-9fe8-3b4a71552c41}
systemData  : @{createdBy=; createdByType=; createdAt=3/10/2022 2:22:58 PM; lastModifiedBy=9cdead84-a844-4324-93f2-b2e6bb768d07; lastModifiedByType=Application; lastModifiedAt=3/10/2022 3:16:48 PM}
vmResources : @{name=FJAVDAFC-9; id=/subscriptions/##############/resourceGroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.Compute/virtualMachines/FJAVDAFC-9; type=Microsoft.Compute/virtualMachines;
              location=francecentral; tags=; properties=; resources=System.Object[]}
imageInfo   :

**Comment by srozemuller** [comment]
@iacavd did you select the correct subscription? Normally this event occurs when you are in de wrong context (subscription selected in PowerShell) 

Get-Azsubscription
Set-AzContext correctSub

**Comment by iacavd** [comment]
@srozemuller  despite setting the context, still seeing the same issue 

PS Q:\AzAvd> Set-AzContext -Subscription ##########################

Name                                     Account                                                   SubscriptionName                                         Environment                                              TenantId
----                                     -------                                                   ----------------                                         -----------                                              --------
CCE-Azure-VDI (##########-46e2-a996-… ##################                                         CCE-Azure-VDI                                            AzureCloud                                               ############-0ffe9ae68fef

PS Q:\AzAvd> Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName | Select-Object vmLatestVersion, hostpoolName, sessionhostName, currentImageVersion, lastVersion
WARNING: Someting went wrong when crawling for info, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}
WARNING: Someting went wrong when crawling for info, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}
WARNING: Someting went wrong when crawling for info, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}
WARNING: Someting went wrong when crawling for info, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}

vmLatestVersion     :
hostpoolName        :
sessionhostName     :
currentImageVersion :
lastVersion         :

vmLatestVersion     :
hostpoolName        :
sessionhostName     :
currentImageVersion :
lastVersion         :

vmLatestVersion     :
hostpoolName        :
sessionhostName     :
currentImageVersion :
lastVersion         :

vmLatestVersion     :
hostpoolName        :
sessionhostName     :
currentImageVersion :
lastVersion         :


PS Q:\AzAvd>

**Comment by iacavd** [comment]
So this is how resources are structures 

RG-Shared-Resources (AzComputeGallery, Log Analytics , DiagnosticLogs Storage Account, ComputeGallery Images) 
RG-AVDArm-Resource (AVD HostPool/WorkSpaec/AppGroup/HostVMs/FSLogix Storage Account)

**Comment by srozemuller** [comment]
@iacavd ok cool, working on it. thanx

**Comment by srozemuller** [comment]
@iacavd I did take a look but must say I didn't get any error. Also, my environment has different resource groups. It looks like something in your PowerShell environment refers a resource group to $(AVD.SharedImageGalleryResourceGroup). Can you explain that variable? if the resource group is not found, I expect the resource group name in the error

**Comment by iacavd** [comment]
Well that's not possible as I have tried it on 3 different machines, with different Operating systems, including an azure VM 
and the script is a single liner 
I have even uploaded files to Azure Shell and I got the same results

**Comment by srozemuller** [comment]
Are you able to share the script with me?

> @srozemuller Well that's not possible as I have tried it on 3 different machines, with different Operating systems, including an azure VM and the script is a single liner I have even uploaded files to Azure Shell and I got the same results

Are you able to share the script with me?

**Comment by iacavd** [comment]
`[CmdletBinding()]
param (
    [Parameter(Mandatory = $true)]
    [String]
    $HostPoolName,
    [Parameter(Mandatory = $true)]
    [String]
    $AVDArmResourcesResourceGroupName
)


#Install-Module Az.Avd
#Import-Module Az.Avd

#Get-AvdImageVersionStatus -HostpoolName  -ResourceGroupName  [-NotLatest] []
#Get-AvdImageVersionStatus -HostpoolName <String> -ResourceGroupName <String> [-SessionHostName <String>] [-NotLatest] [<CommonParameters>]


Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName | Select-Object vmLatestVersion, hostpoolName, sessionhostName, currentImageVersion, lastVersion


Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName -NotLatest | ForEach-Object { Update-AvdSessionhostDrainMode -HostpoolName $_.Hostpoolname -ResourceGroupName $AVDArmResourcesResourceGroupName -SessionHostName $_.sessionHostName -AllowNewSession $true }

#Remove Session Host from Host Pool
Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName -NotLatest | ForEach-Object {Remove-AvdSessionhost -HostpoolName $_.Hostpoolname -ResourceGroupName $AVDArmResourcesResourceGroupName -SessionHostName $_.sessionHostName}

#Remove VM and Associated Resources
Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName -NotLatest | ForEach-Object {
    $sessionHostInfo = @{
        HostpoolName = $_.HostpoolName
        ResourceGroupName = $AVDArmResourcesResourceGroupName
        SessionHostName = $_.SessionHostName
    }
    
    $sessionHost = Get-AvdSessionHostResources @sessionHostInfo
    Remove-AzResource -ResourceId $sessionHost.Id -Force
    Remove-AzResource -ResourceId $sessionHost.StorageProfile.OsDisk.ManagedDisk.id -Force
    Remove-AzResource -ResourceId (Get-AvdNetworkInfo @sessionHostInfo).nicId -Force
}`

**Comment by iacavd** [comment]
@srozemuller I am open to having a teams session to go through this together if that's ok with you ?
I am in central European timezone

**Comment by srozemuller** [comment]
@iacavd  I updated the code. Could you download the v2.1.4-beta.0 release please. https://github.com/srozemuller/AzAvd/releases/tag/v2.1.4-beta.0

While importing the Az.Avd module. please check if you have loaded version 2.1.4. Otherwise, import the module with import-module .\az.avd.psm1 -force and check with Get-Module if Az.Avd has version 2.1.4. 

Then run  Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName again. 

In the error, there is also an URL posted. This is the URL where the module searches for versions. 
Hopefully, this will clarify. From this point, I don't have a clue where something is wrong. I do have the same environment (with separated resource groups) and did not get any errors. 

Another strange thing is the $(AVD.SharedImageGalleryResourceGroup). I do not use that variable. Also, this variable is not declared the correct way. (Should be like $($AVD.SharedImageGalleryResourceGroup). Where $AVD is an object and SharedImageGalleryResourceGroup is an object in the variable. The error as shown suggests the command is searching for a resource group called $(AVD.SharedImageGalleryResourceGroup) which does not exist.

**Comment by iacavd** [comment]
```
PS Q:\AzAvd> Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName
WARNING: Someting went wrong when crawling for info at url https://management.azure.com/versions?api-version=2022-01-03, {"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}
WARNING: Someting went wrong when crawling for info at url https://management.azure.com/versions?api-version=2022-01-03, {"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}

name        : AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-0.##########
id          : /subscriptions/##########/resourcegroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.DesktopVirtualization/hostpools/AVD-HostPool-SND-FJ-POC-AFC-01/sessionhosts/FJAVDAFC-0.##########
type        : Microsoft.DesktopVirtualization/hostpools/sessionhosts
properties  : @{lastHeartBeat=17/03/2022 17:30:18; statusTimestamp=17/03/2022 17:15:00; lastUpdateTime=17/03/2022 17:15:00; sessions=0; agentVersion=1.0.4119.1500; allowNewSession=True; assignedUser=; status=Available; osVersion=10.0.19043;
              sxSStackVersion=rdp-sxs220104110; updateState=Succeeded; updateErrorMessage=; sessionHostHealthCheckResults=System.Object[];
              resourceId=/subscriptions/##########/resourceGroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.Compute/virtualMachines/FJAVDAFC-0; virtualMachineId=6d3ff07e-f24d-4dd0-b5d9-38795ed0f023;
              objectId=e55f41d0-e3da-4e59-95be-c661318fd410}
systemData  : @{createdBy=; createdByType=; createdAt=17/03/2022 17:01:59; lastModifiedBy=; lastModifiedByType=; lastModifiedAt=}
vmResources : @{name=FJAVDAFC-0; id=/subscriptions/##########/resourceGroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.Compute/virtualMachines/FJAVDAFC-0; type=Microsoft.Compute/virtualMachines; location=francecentral;
              tags=; properties=; resources=System.Object[]}
imageInfo   :

name        : AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-1.##########
id          : /subscriptions/##########/resourcegroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.DesktopVirtualization/hostpools/AVD-HostPool-SND-FJ-POC-AFC-01/sessionhosts/FJAVDAFC-1.##########
type        : Microsoft.DesktopVirtualization/hostpools/sessionhosts
properties  : @{lastHeartBeat=17/03/2022 17:30:21; statusTimestamp=17/03/2022 17:15:04; lastUpdateTime=17/03/2022 17:15:04; sessions=0; agentVersion=1.0.4119.1500; allowNewSession=True; assignedUser=; status=Available; osVersion=10.0.19043;
              sxSStackVersion=rdp-sxs220104110; updateState=Succeeded; updateErrorMessage=; sessionHostHealthCheckResults=System.Object[];
              resourceId=/subscriptions/##########/resourceGroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.Compute/virtualMachines/FJAVDAFC-1; virtualMachineId=c037f310-0327-48b6-81f6-1837a4780527;
              objectId=d6702c60-f725-4ce8-bba4-c41584cc540c}
systemData  : @{createdBy=; createdByType=; createdAt=17/03/2022 17:02:13; lastModifiedBy=; lastModifiedByType=; lastModifiedAt=}
vmResources : @{name=FJAVDAFC-1; id=/subscriptions/##########/resourceGroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.Compute/virtualMachines/FJAVDAFC-1; type=Microsoft.Compute/virtualMachines; location=francecentral;
              tags=; properties=; resources=System.Object[]}
imageInfo   :


PS Q:\AzAvd>
```

**Comment by iacavd** [comment]
yeah exactly thats what i was wondering , may be its looking through deployment template ? (because in deployment template for HostPool/VM we use this to refer to source image from shared image gallery)

**Comment by srozemuller** [comment]
Thank you for providing this information. I think I just found something. It is not common sense that every VM has also a version as an image reference. Sometimes VM has a version selected, sometimes just the image (which is the latest). I build a check if a version is selected or not. 
This should fix the first error with no imageInfo at all. Could you test with the new code? 
(Just download the code from the [[70edd71](https://github.com/srozemuller/AzAvd/commit/70edd71e31d965045eb4f4e35d9b2e7493ffe760)] and import the module again.

**Comment by iacavd** [comment]
@srozemuller  sorry i missed your 2nd last message will check and update you, thanks for all the help and effort
